# Generated by Django 3.0.5 on 2024-01-05 15:42

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20240105_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='category'),
        ),
    ]
