# Generated by Django 3.0.5 on 2024-01-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20240124_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
